### ISSUE TITLE
Tar creation error for small traces

### ISSUE THREAD

**Issue by brycepg** [intel/ioprof#1]
ioprof fails when creating traces < 3 seconds long

```
~/ioprof> ioprof.py -m trace -d /dev/nvme0n1  -r 2
Mapping files to block locations                
Creating tarball nvme0n1.tar
tar -cf nvme0n1.tar blk.out.nvme0n1.*.gz fdisk.nvme0n1  &> /dev/null
ERROR: failed to tarball nvme0n1.tar

```

(this only happens on the python version)

**Comment by bjdonie** [comment]
Great catch!  Indeed the tool breaks up long blktrace runs into 3 second bursts to minimize the potential for overrunning the buffer.  I’ll investigate.

Thanks,
Benjamin Donie
Intel Corporation | SSD Test Development Engineer

**Comment by bjdonie** [comment]
`sudo ioprof/ioprof.pl -m trace -d /dev/sda1 -r 2
ioprof/ioprof.pl (2.0.5)

FINISHED tracing: sda1.tar
Please use this file with ioprof/ioprof.pl -m post -t sda1.tar to create a report
`

This should be resolved on the latest commit.  I'm closing out this issue.  It was tested on Ubuntu 16.04 LTS and Ubuntu 18.04 LTS
